# Color settings
#set -as terminal-overrides ',*:Setul=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
#set -ag terminal-overrides ",xterm-256color:RGB"
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*:RGB"

# Enable mouse and keyboard
set -g mouse on
set -g set-clipboard on

# Rebind prefix
unbind C-b
set -g prefix C-p
bind C-p send-prefix

# Rebind splitting
unbind %
unbind '"'
unbind h
unbind v
bind H split-window -h
bind V split-window -v

# Vim keys for pane navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# dwm style pane resizing
bind -n M-H resize-pane -L 3
bind -n M-J resize-pane -D 3
bind -n M-K resize-pane -U 3
bind -n M-L resize-pane -R 3

# Status bar general appearance 
set -g status-style "bg=default,fg=white"
set -g status-position top # can be set to 'top' if you prefer

# Left side of the status bar (Session name)
set -g status-left-length 40
set -g status-left "#[fg=green,bold][#S] #[default]"

# Right side of the status bar (Date and Time)
set -g status-right-length 50
set -g status-right "#[fg=white]%Y-%m-%d  %H:%M "

# Window status format (Inactive windows)
set -g window-status-format " #I:#W "

# Window status format
set -g window-status-current-format "#[bg=green,fg=black,bold] #I:#W #[default]"

# Update the status bar every second
set -g status-interval 1

# Neovim optimizations
set -s escape-time 10
set -g focus-events on

# Start windows at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Rebind window switch to numbers
bind -n M-! select-window -t 1
bind -n M-@ select-window -t 2
bind -n M-# select-window -t 3
bind -n M-$ select-window -t 4
bind -n M-% select-window -t 5
bind -n M-^ select-window -t 6
bind -n M-& select-window -t 7
bind -n M-* select-window -t 8
bind -n M-( select-window -t 9
